volumes:
  n8n_storage:
  postgres_storage:
  qdrant_storage:
  localai_storage:

networks:
  autoreel:

x-n8n: &service-n8n
  build:
    context: .
    dockerfile: Dockerfile
  networks: ["autoreel"]
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=postgres
    - DB_POSTGRESDB_USER=${POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    - N8N_DIAGNOSTICS_ENABLED=false
    - N8N_PERSONALIZATION_ENABLED=false
    - N8N_ENCRYPTION_KEY
    - N8N_USER_MANAGEMENT_JWT_SECRET
    - PATH=/google-cloud-sdk/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
    - CLOUDSDK_CONFIG=/home/node/.config/gcloud
    - GENERIC_TIMEZONE=Asia/Ho_Chi_Minh
    - WEBHOOK_URL=https://n8n.autoreel.io.vn/
    - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
    - N8N_PUSH_BACKEND=websocket
    - N8N_RUNNERS_ENABLED=true
    - N8N_DEFAULT_BINARY_DATA_MODE=filesystem

services:
  postgres:
    image: postgres:16-alpine
    hostname: postgres
    networks: ["autoreel"]
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - postgres_storage:/var/lib/postgresql/data
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -h localhost -U ${POSTGRES_USER} -d ${POSTGRES_DB}",
        ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *service-n8n
    hostname: n8n
    container_name: n8n
    restart: unless-stopped
    ports:
      - 5678:5678
    volumes:
      - n8n_storage:/home/node/.n8n
      - ./n8n/backup:/backup
      - ./shared:/data/shared
    depends_on:
      postgres:
        condition: service_healthy

  qdrant:
    image: qdrant/qdrant
    hostname: qdrant
    container_name: qdrant
    networks: ["autoreel"]
    restart: unless-stopped
    ports:
      - 6333:6333
    volumes:
      - qdrant_storage:/qdrant/storage

  localai:
    image: localai/localai:latest-gpu-nvidia-cuda-12
    container_name: localai
    hostname: localai
    networks: ["autoreel"]
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - localai_storage:/build/models
    environment:
      - MODELS_PATH=/build/models
      - REBUILD=TRUE
    command:
      - dreamshaper
      - llama-3.2-3b-instruct:q8_0
      - whisper-large-q5_0
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: ["0"]
              capabilities: [gpu]
